/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import "SEECPhaseWebViewController.h"

//new library
#import "JSONKit.h"

@interface SEECPhaseWebViewController ()

@end

@implementation SEECPhaseWebViewController


@synthesize exercises;
@synthesize responseData;



- (id)initWithStyle:(UITableViewStyle)style
{
    self = [super initWithStyle:style];
    
    
    //to unable scroll
    self.tableView.scrollEnabled = YES;
    
    
    //adjust in popover
    self.contentSizeForViewInPopover = CGSizeMake(250.0, 300.0);
    
    self.title = @"Ronda en Web";
    if (self) {
        // Custom initialization
    }
    return self;
}





- (void)viewDidLoad
{

    
    //get phase oroginal format catalog
    //http://www.havo.com.mx/ipad/seec_phaseCatalog.json
    
    //get phase from seec
    //http://201.175.46.102/wcfpwc/Replica.svc/phase
    
    //get phase with light format
    //http://www.havo.com.mx/ipad/document.json
    
    //get Phases from production
    //https://seec.bestoption.com.mx/
    
    
    
    responseData = [[NSMutableData data] retain];
   
    
    
    [self conectionpost];
    
    
    [super viewDidLoad];
    
}



- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}





-(void)conectionpost{

    //Create String
    NSString *var1 =@"waitTime=";
    NSString *var2 =@"&cover=";
    
    NSString *wait = [var1 stringByAppendingString:@"waitTimeValue"];
    NSString *co = [var2 stringByAppendingString:@"&coverValue"];
    
    
    NSMutableURLRequest *request =
    [[NSMutableURLRequest alloc] initWithURL:
     [NSURL URLWithString:@"https://seec.bestoption.com.mx/wcfpwc/Replica.svc/phase"]];
    
    [request setHTTPMethod:@"POST"];
    
    NSString *postString = [wait stringByAppendingString:co];
    
    [request setValue:[NSString
                       stringWithFormat:@"%d", [postString length]]
   forHTTPHeaderField:@"Content-length"];
    
    [request setHTTPBody:[postString
                          dataUsingEncoding:NSUTF8StringEncoding]];
    
    [[NSURLConnection alloc] initWithRequest:request delegate:self];
    
    
}





- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{

    return [exercises count];
    
    
}




- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{

    //create a cell
    UITableViewCell *cell = [[UITableViewCell alloc]
                             initWithStyle:UITableViewCellStyleDefault
                             reuseIdentifier:@"cell"];
    
    NSDictionary *currentObject = [self.exercises objectAtIndex:indexPath.row];
    
    
    cell.textLabel.text = [NSString stringWithFormat:@"%@", [currentObject valueForKey:@"phaseNum"]];
    
    
    
    // return it
    return cell;
    
     
}



- (void)connection:(NSURLConnection *)connection didReceiveResponse:(NSURLResponse *)response {
    [responseData setLength:0];
}





- (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data {
    [responseData appendData:data];
}





- (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error {
    NSLog(@"Connection failed: %@", [error description]);
}





- (void)connectionDidFinishLoading:(NSURLConnection *)connection {
    [connection release];
    
    NSString *responseString = [[NSString alloc] initWithData:responseData encoding:NSUTF8StringEncoding];
    [responseData release];
    
   
    NSLog(@" responding from web %@", responseString);
    
    
    //using json kit
    NSDictionary *dictionary = [responseString objectFromJSONString];
    
    //the root in json
    NSArray *response = [dictionary objectForKey:@"phases"];
    
    exercises = [[NSArray alloc] initWithArray:response];
    
}



- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    // Return the number of sections.
    return 1;
}





#pragma mark - Table view delegate

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
   
    //--
    
    NSDictionary *currentObject = [self.exercises objectAtIndex:indexPath.row];
    
   
    NSString *phaseNum = [NSString stringWithFormat:@"%@", [currentObject valueForKey:@"phaseNum"]];
    
    
    
    NSLog(@" fase num  %@", phaseNum);
    
    
    NSLog(@" index at   %d", indexPath.row );
    
    
    //---
    //        Notification from web wee need to tune
    //---  
    
    NSArray *objKeys = [NSArray arrayWithObjects: @"label", @"id",  nil];
    
        
    
   // NSArray *branchObjects = [NSArray arrayWithObjects:@"label", phaseNum, nil];
    
    NSArray *branchObjects = [NSArray arrayWithObjects:phaseNum , phaseNum, nil];
    
    
    
    NSDictionary *branchDictionary = [NSDictionary dictionaryWithObjects:branchObjects forKeys:objKeys];
    
    
    [[NSNotificationCenter defaultCenter] postNotificationName:@"phases" object:branchDictionary];
    


}

@end
