/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import "SEECResponsibleAreaViewController.h"

#import "SEECUser.h"
#import "AFJSONUtilities.h"
#import "NSData+Persistence.h"

@interface SEECResponsibleAreaViewController ()

@end

@implementation SEECResponsibleAreaViewController
@synthesize scroller;



@synthesize branchNameLabel;


@synthesize D1_firstName;
@synthesize D1_lastName;


@synthesize D2_firstName;
@synthesize D2_lastName;


@synthesize D3_firstName;
@synthesize D3_lastName;


@synthesize D4_firstName;
@synthesize D4_lastName;


@synthesize D5_firstName;
@synthesize D5_lastName;


@synthesize D6_firstName;
@synthesize D6_lastName;


@synthesize D7_firstName;
@synthesize D7_lastName;


@synthesize D8_firstName;
@synthesize D8_lastName;



@synthesize D9_firstName;
@synthesize D9_lastName;


@synthesize D10_firstName;
@synthesize D10_lastName;


@synthesize D11_firstName;
@synthesize D11_lastName;


@synthesize D12_firstName;
@synthesize D12_lastName;


@synthesize D13_firstName;
@synthesize D13_lastName;


@synthesize D14_firstName;
@synthesize D14_lastName;


@synthesize D15_firstName;
@synthesize D15_lastName;








- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
}



- (void)viewDidLoad
{
    [super viewDidLoad];
     [scroller setScrollEnabled:YES];
	// Do any additional setup after loading the view.
    
    branchNameLabel.text = [[SEECUser sharedInstance]bName ];
    
    [self loadResponsibleArea];
    
}




-(void)loadResponsibleArea{

    
   
       // "LK_departmentId": "1",
       // "departmentName": "Presidencia"

    
    [self recoverInfo2Form:@"1" :D1_firstName :D1_lastName];
    
    
    
       // "LK_departmentId": "2",
       // "departmentName": "Direccion"
    
    
     [self recoverInfo2Form:@"2" :D2_firstName :D2_lastName];
    
    
       // "LK_departmentId": "3",
       // "departmentName": "Gerente General"
    
    
     [self recoverInfo2Form:@"3" :D3_firstName :D3_lastName];
 
    
    
    
       //  "LK_departmentId": "4",
       // "departmentName": "Gerente de Ventas"
   
     [self recoverInfo2Form:@"4" :D4_firstName :D4_lastName];
    
    
    
       // "LK_departmentId": "5",
       // "departmentName": "Gerente de Servicio"
    
    
     [self recoverInfo2Form:@"5" :D5_firstName :D5_lastName];
    
    
        //"LK_departmentId": "6",
        //"departmentName": "Gerente de Finanzas"
    
    
     [self recoverInfo2Form:@"6" :D6_firstName :D6_lastName];
    
        // "LK_departmentId": "7",
        //"departmentName": "Gerente de Mercadotecnia"
    
     [self recoverInfo2Form:@"7" :D7_firstName :D7_lastName];
    
    
    
        //"LK_departmentId": "8",
        //"departmentName": "Gerente de Refacciones"
    
     [self recoverInfo2Form:@"8" :D8_firstName :D8_lastName];
    
    
        //"LK_departmentId": "9",
        //"departmentName": "Gerente de Flotillas"
    
     [self recoverInfo2Form:@"9" :D9_firstName :D9_lastName];
    
    
        //"LK_departmentId": "10",
        //"departmentName": "Gerente de ProShop"
    
     [self recoverInfo2Form:@"10" :D10_firstName :D10_lastName];
    
        //"LK_departmentId": "11",
        //"departmentName": "Gerente de Capacitación"
   
     [self recoverInfo2Form:@"11" :D11_firstName :D11_lastName];
    
        //"LK_departmentId": "12",
        //"departmentName": "Vendedor"
   
     [self recoverInfo2Form:@"12" :D12_firstName :D12_lastName];
    
        //"LK_departmentId": "13",
        //"departmentName": "ADPC"
    
     [self recoverInfo2Form:@"13" :D13_firstName :D13_lastName];
   
        // "LK_departmentId": "14",
        // "departmentName": "EPCI"
    
    [self recoverInfo2Form:@"14" :D14_firstName :D14_lastName];
    
        //"LK_departmentId": "15",
        //"departmentName": "FI"
    
     [self recoverInfo2Form:@"15" :D15_firstName :D15_lastName];
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    




}



//try to optimize this function

-(void)recoverInfo2Form :  (NSString *) departmentId
                        :  (UITextField *) tf_firstName
                        :  (UITextField *) tf_lastName {


    
    NSLog(@" branch id %@",[[SEECUser sharedInstance]branchId]);
    
    
    
    NSPredicate *predicResponsible = [NSPredicate predicateWithFormat:@"FK_branchId == %@ AND FK_departmentId == %@", [[SEECUser sharedInstance]branchId] ,departmentId ];
    
    
    
    NSDictionary *recoverInfoResp  =  [self recoverInfo:                                                                @"seec_owner" : predicResponsible : @"dataroot" : @"seec_owner" ];
    
    
    //full name
   
    tf_firstName.text=[NSString stringWithFormat:@"%@", [recoverInfoResp valueForKey:@"firstName"]];
    tf_lastName.text=[NSString stringWithFormat:@"%@", [recoverInfoResp valueForKey:@"lastName"]];
    
        
    

}




- (void)viewDidUnload
{
    [self setScroller:nil];
    [super viewDidUnload];
    // Release any retained subviews of the main view.
}




- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return (interfaceOrientation == UIInterfaceOrientationLandscapeRight);
}



- (IBAction)scrollOn:(id)sender{
    
    NSLog(@"on");
    [scroller setContentOffset:CGPointMake(0, 500) animated:YES];
    
}


- (IBAction)scrollOff:(id)sender{
    NSLog(@"off");
    [scroller setContentOffset:CGPointMake(0, 0) animated:YES];
    
    
}



- (IBAction)save:(id)sender{
    NSLog(@"dismiss modal...for back");
    [self dismissModalViewControllerAnimated:YES];


}


- (IBAction)back:(id)sender{
    NSLog(@"dismiss modal...for back");
    [self dismissModalViewControllerAnimated:YES];


}





-(NSDictionary *) recoverInfo: (NSString *)    fileJson
                             : (NSPredicate *) predicate
                             : (NSString *)    dataRoot
                             : (NSString *) setValue{
    
    NSURL *url = [[NSBundle mainBundle] URLForResource:fileJson withExtension:@"json"];
    
    NSData *data = [NSData dataWithContentsOfURL:url];
    
    NSError *error = nil;
    
    NSDictionary *response = AFJSONDecode(data, &error);
    
    
    NSArray *items =[[[response valueForKey:dataRoot] valueForKey:setValue] filteredArrayUsingPredicate:predicate];
    
    
    NSDictionary *currentObject = [ items objectAtIndex:0];
    
    
    return currentObject;
    
}






- (void)dealloc {
    [scroller release];
    [super dealloc];
}


@end
