/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import "SEECPhotoGallerySource.h"
#import "UIImage+Persistence.h"
#import "NSArray+Persistence.h"

@interface SEECPhotoGallerySource ()

@end

@implementation SEECPhotoGallerySource


-(id)initWithEvaluationID:(NSString *)evaluationID
{
    NSArray *arrayOfEvidence = [NSArray arrayFromFileName:@"seec_evidenceFile.json"];
    
    if (!arrayOfEvidence) return nil;
    
    self = [super init];
    
    if (self)
    {
        NSMutableArray *images = [NSMutableArray array];
        
        for (NSDictionary *imageData in arrayOfEvidence)
        {
            if (![[imageData valueForKey:@"FK_evaluationID"] isEqualToString:evaluationID]) continue;
                
            NSString *imagePath = [UIImage imagePathFromFileName:[imageData valueForKey:@"fileName"]];
            
            if (imagePath)
            {
                [images addObject:imagePath];
            }
        }
        
        _allPhotos = [[NSMutableArray alloc] initWithArray:images];
        
    }
    
    return self;
    
}

-(id)initWithTest
{
    self = [super init];
    
    if (self)
    {
        
        NSMutableArray *all3Photos = [[NSMutableArray alloc] init];
        
        for (int i=0; i<5; ++i)
        {
            NSString *imageFileName = [NSString stringWithFormat:@"ExamplePhoto_%d", i];
            
            NSString *anExamplePhotoURL = [[NSBundle mainBundle] pathForResource:imageFileName
                                                                          ofType:@"JPG"];
            
            [all3Photos addObject:anExamplePhotoURL];
        }
        
        // Darle click a una foto y subirla.
        _allPhotos=[[NSMutableArray alloc] initWithArray:all3Photos];        
    }
    
    return self;
}


#pragma mark - FGalleryViewControllerDelegate

// Needed methods used to populate photographs in photo gallery

-(int)numberOfPhotosForPhotoGallery:(FGalleryViewController *)gallery
{
    return [self.allPhotos count];
}

-(FGalleryPhotoSourceType)photoGallery:(FGalleryViewController *)gallery sourceTypeForPhotoAtIndex:(NSUInteger)index
{
    // Since all images will be retrieved locally, we can return 'FGalleryPhotoSourceTypeLocal' as a constant.
    return FGalleryPhotoSourceTypeLocal;
}

-(NSString *)photoGallery:(FGalleryViewController *)gallery
     filePathForPhotoSize:(FGalleryPhotoSize)size
                  atIndex:(NSUInteger)index
{
    // This array contains the filepath of the files. Could contain an array of NSDictionaries with
    return [self.allPhotos objectAtIndex:index];
}


@end
