/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import <UIKit/UIKit.h>

@interface SEECAuditoriaViewController : UIViewController


@property (retain) UIPopoverController *popOverController;


- (IBAction)goEvaluation:(id)sender;


@property (retain, nonatomic) IBOutlet UIImageView *silverSelected;

@property (retain, nonatomic) IBOutlet UIImageView *GoldenSelected;



- (IBAction)ssicsi:(id)sender;

- (IBAction)DataOfDealer:(id)sender;

- (IBAction)SituationReport:(id)sender;

- (IBAction)Responsable:(id)sender;

- (IBAction)GoldCertification:(id)sender;

- (IBAction)SilverCertification:(id)sender;

- (IBAction)Phases:(UIButton *)sender;

- (void)PhaseWithNotification:(NSNotification *)notification;



@property (retain, nonatomic) IBOutlet UITextView *adressDealer;
@property (retain, nonatomic) IBOutlet UITextView *phoneDealer;

@property (retain, nonatomic) IBOutlet UITextView *dateDealer;

@property (retain, nonatomic) IBOutlet UILabel *nameDealer;

@property (retain, nonatomic) IBOutlet UILabel *phaseLabel;


@end
