/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 

#import "SEECAlertViewController.h"

@interface SEECAlertViewController ()

@end




@implementation SEECAlertViewController

@synthesize branchLabel;
@synthesize directionLabel;
@synthesize slider;
@synthesize operationLabel;
@synthesize phaseLabel;
@synthesize entity;



- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
}

- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view.
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}



-(IBAction)changeSlider:(id)sender{

    if (slider.on == YES)
    {
      NSArray *keys = [NSArray arrayWithObjects: @"entity",nil];
      NSArray *vals = [NSArray arrayWithObjects: entity, nil];
      NSDictionary *dic = [NSDictionary dictionaryWithObjects:vals forKeys:keys];
      [[NSNotificationCenter defaultCenter] postNotificationName:@"alert" object:dic];
      [self dismissModalViewControllerAnimated:YES];
    }
    else
    {
        // Other code...
        NSLog(@"en NOT"); 
    
    }
    

}


- (IBAction)back:(id)sender{
    NSLog(@"dismiss modal...for back");
    [self dismissModalViewControllerAnimated:YES];
    
   
}




- (void)dealloc {


    [super dealloc];


}



- (void)viewDidUnload {
    [self setBranchLabel:nil];
    [self setDirectionLabel:nil];
    [self setSlider:nil];
    [self setOperationLabel:nil];
    [self setPhaseLabel:nil];
    [super viewDidUnload];
}
@end
