/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import <Foundation/Foundation.h>

@interface SEECUser : NSObject{

    //--login
    NSString *userId;
    NSString *userName;
    
    //--auditoria
    NSString *stateSelected;
    NSString *citySelected;
    NSString *dealerSelected;
    NSString *phaseNumLabel;
    
    //dealer
    NSString *saleType;
    NSString *subZone;
    NSString *branchType;
    NSString *branchId;
    NSString *adress;
    NSString *phone;
    NSString *bName;
    
    
       
    //seec activity
    NSString *obj;
    NSString *mth;
    NSString *act;
    NSString *code;
    NSString *std;
    NSString *evid;
    NSString *typeOfBreach;
    
    
    
    /////seec_evaluation
    NSString *LK_evaluationId;
    NSString *FK_userId;
	NSString *FK_manualId;
	NSString *FK_standardId;
	NSString *FK_activityId;
	NSString *FK_branchId;
	NSString *FK_departmentId;
	NSString *FK_ownerId;
	NSString *phaseNum;
	NSString *reached;
	NSString *notReached;
	NSString *notApplicable;
	NSString *certificationLevel;
	NSString *commentTitle;
	NSString *comment;
	NSString *recommendation;
	NSString *createdDate;
	NSString *actionPlan;
	NSString *estimatedImpDate;
	NSString *actionPlanDate;
	NSString *actionPlanComment;
	NSString *commentDate;
	NSString *actionPlanApprove;
	NSString *furtherContribution;
	NSString *tracking;
    NSString *specialStandard;
    
    //seec search
    NSString *searchType;
    NSString *searchValue;
    
    ///seee_auditDate
    NSString *LK_auditDateId;
    NSString *auditDate;
    
    ///seec_owner
    NSString *isvNumber;
	NSString *firstName;
	NSString *lastName;
    NSString *ownerUser;
    
    
	///////seec_indicator
	NSString *LK_indCveId;
	NSString *fMonth;
	NSString *sMonth;
	NSString *tMonth;
	NSString *isv_R1;
	NSString *isc_R1;
	NSString *isv_R2;
	NSString *isc_R2;
	NSString *isv_R3;
	NSString *isc_R3;
    NSString *cMonth;
    NSString *isv_Current;
	NSString *isc_Current;
   
    //filing
    NSString *fileName_;
    NSString *evaluationID_;
    
}


//---login
@property (nonatomic, retain) NSString *userId;
@property (nonatomic, retain) NSString *userName;

//--audit

@property (nonatomic, retain) NSString *stateSelected;
@property (nonatomic, retain) NSString *citySelected;
@property (nonatomic, retain) NSString *dealerSelected;
@property (nonatomic, retain) NSString *phaseNumLabel;

//---dealer
@property (nonatomic, retain) NSString *saleType;
@property (nonatomic, retain) NSString *subZone;
@property (nonatomic, retain) NSString *branchType;
@property (nonatomic, retain) NSString *branchId;
@property (nonatomic, retain) NSString *adress;
@property (nonatomic, retain) NSString *phone;
@property (nonatomic, retain) NSString *bName;

//--activity
@property (nonatomic, retain) NSString *obj;
@property (nonatomic, retain) NSString *mth;
@property (nonatomic, retain) NSString *act;
@property (nonatomic, retain) NSString *code;
@property (nonatomic, retain) NSString *std;
@property (nonatomic, retain) NSString *evid;
@property (nonatomic, retain) NSString *typeOfBreach;

//--evaluation
@property (nonatomic, retain) NSString *LK_evaluationId;
@property (nonatomic, retain) NSString *FK_userId;
@property (nonatomic, retain) NSString *FK_manualId;
@property (nonatomic, retain) NSString *FK_standardId;
@property (nonatomic, retain) NSString *FK_activityId;
@property (nonatomic, retain) NSString *FK_branchId;
@property (nonatomic, retain) NSString *FK_departmentId;
@property (nonatomic, retain) NSString *FK_ownerId;
@property (nonatomic, retain) NSString *phaseNum;
@property (nonatomic, retain) NSString *reached;
@property (nonatomic, retain) NSString *notReached;
@property (nonatomic, retain) NSString *notApplicable;
@property (nonatomic, retain) NSString *certificationLevel;
@property (nonatomic, retain) NSString *commentTitle;
@property (nonatomic, retain) NSString *comment;
@property (nonatomic, retain) NSString *recommendation;
@property (nonatomic, retain) NSString *createdDate;
@property (nonatomic, retain) NSString *actionPlan;
@property (nonatomic, retain) NSString *estimatedImpDate;
@property (nonatomic, retain) NSString *actionPlanDate;
@property (nonatomic, retain) NSString *actionPlanComment;
@property (nonatomic, retain) NSString *commentDate;
@property (nonatomic, retain) NSString *actionPlanApprove;
@property (nonatomic, retain) NSString *furtherContribution;
@property (nonatomic, retain) NSString *tracking;
@property (nonatomic, retain) NSString *specialStandard;


//--search value
@property (nonatomic, retain) NSString *searchType;
@property (nonatomic, retain) NSString *searchValue;



//////seee_auditDate

@property (nonatomic, retain) NSString *LK_auditDateId;
@property (nonatomic, retain) NSString *auditDate;


////seec_owner

@property (nonatomic, retain) NSString *LK_ownerId;
@property (nonatomic, retain) NSString *isvNumber;
@property (nonatomic, retain) NSString *firstName;
@property (nonatomic, retain) NSString *lastName;
@property (nonatomic, retain) NSString *ownerUser;


////seec_indicator
@property (nonatomic, retain) NSString *LK_indCveId;
@property (nonatomic, retain) NSString *fMonth;
@property (nonatomic, retain) NSString *sMonth;
@property (nonatomic, retain) NSString *tMonth;
@property (nonatomic, retain) NSString *isv_R1;
@property (nonatomic, retain) NSString *isc_R1;
@property (nonatomic, retain) NSString *isv_R2;
@property (nonatomic, retain) NSString *isc_R2;
@property (nonatomic, retain) NSString *isv_R3;
@property (nonatomic, retain) NSString *isc_R3;
@property (nonatomic, retain) NSString *cMonth;
@property (nonatomic, retain) NSString *isv_Current;
@property (nonatomic, retain) NSString *isc_Current;


@property (nonatomic, retain) NSString *fileName_;
@property (nonatomic, retain) NSString *evaluationID_;


//login
- (id)initUserId:(NSString *)userId_;
- (id)initUserName:(NSString *)userName_;



//Audit
- (id)initState:(NSString *)statein;
- (id)initCity:(NSString *)cityin;
- (id)initDealer:(NSString *)dealerin;
- (id)initPhaseLabel:(NSString *)phaseNumLabelin;


//---dealer
- (id)initSaleType:(NSString *)saletypein;
- (id)initSubZone:(NSString *)subZonein;
- (id)initBranchType:(NSString *)branchTypein;
- (id)initBranchId:(NSString *)branchIdin;
- (id)initAdress:(NSString *)adressin;
- (id)initPhone:(NSString *)phonein;
- (id)initbName:(NSString *)bNamein;



//-- activity
- (id)initObj:(NSString *)objin;
- (id)initMth:(NSString *)mthin;
- (id)initAct:(NSString *)actin;
- (id)initCode:(NSString *)codein;
- (id)initStd:(NSString *)Stdin;
- (id)initEvid:(NSString *)evidin;
- (id)inittypeOfBreach:(NSString *)typeOfBreachIn;




//seec evaluation
- (id)initLK_evaluationId:(NSString *)LK_evaluationId_;
- (id)initFK_userId:(NSString *)FK_userId_;
- (id)initFK_manualId:(NSString *)FK_manualId_;
- (id)initFK_standardId:(NSString *)FK_standardId_;
- (id)initFK_activityId:(NSString *)FK_activityId_;
- (id)initFK_branchId:(NSString *)FK_branchId_;
- (id)initFK_departmentId:(NSString *)FK_departmentId_;
- (id)initFK_ownerId:(NSString *)FK_ownerId_;
- (id)initphaseNum:(NSString *)phaseNum_;
- (id)initreached:(NSString *)reached_;
- (id)initnotReached:(NSString *)notReached_;
- (id)initnotApplicable:(NSString *)notApplicable_;
- (id)initcertificationLevel:(NSString *)certificationLevel_;
- (id)initcommentTitle:(NSString *)commentTitle_;
- (id)initcomment:(NSString *)comment_;
- (id)initrecommendation:(NSString *)recommendation_;
- (id)initcreatedDate:(NSString *)createdDate_;
- (id)initactionPlan:(NSString *)actionPlan_;
- (id)initestimatedImpDate:(NSString *)estimatedImpDate_;
- (id)initactionPlanDate:(NSString *)actionPlanDate_;
- (id)initactionPlanComment:(NSString *)actionPlanComment_;
- (id)initcommentDate:(NSString *)commentDate_;
- (id)initactionPlanApprove:(NSString *)actionPlanApprove_;
- (id)initfurtherContribution:(NSString *)furtherContribution_;
- (id)inittracking:(NSString *)tracking_;
- (id)initspecialStandard:(NSString *)specialStandard_;


//seec search
- (id)initSearchWithType:(NSString *)type_;
- (id)initSearchValue:(NSString *)value_;


//seee_auditDate

- (id)initLK_auditDateId:(NSString *)LK_auditDateId_;
- (id)initAuditDate:(NSString *)auditDate_;

//seec_owner


- (id)initIsvNumber:(NSString *)isvNumber_;
- (id)initFirstName:(NSString *)firstName_;
- (id)initLastName:(NSString *)lastName_;
- (id)initOwnerUser:(NSString *)ownerUser_;

//seec_indicator

- (id)initLK_indCveId:(NSString *)LK_indCveId_;
- (id)initFMonth:(NSString *)fMonth_;
- (id)initSMonth:(NSString *)sMonth_;
- (id)initTMonth:(NSString *)tMonth_;
- (id)initIsv_R1:(NSString *)isv_R1_;
- (id)initIsc_R1:(NSString *)isc_R1_;
- (id)initIsv_R2:(NSString *)isv_R2_;
- (id)initIsc_R2:(NSString *)isc_R2_;
- (id)initIsv_R3:(NSString *)isv_R3_;
- (id)initIsc_R3:(NSString *)isc_R3_;
- (id)initCMonth:(NSString *)cMonth_;
- (id)initIsv_Current:(NSString *)isv_Current_;
- (id)initIsc_Current:(NSString *)isc_Current_;


//filing
-(id)initFileName_:(NSString *)fileName_;
-(id)initEvaluationID_:(NSString *)evaluationID_;



//set shared instance no edit
+(SEECUser *) sharedInstance;

@end
