/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import "SEECLoginViewController.h"
#import "SEECReportesViewController.h"
#import "AFJSONUtilities.h"
#import "SEECUser.h"
#import "SEECMenuViewController.h"



@interface SEECLoginViewController ()



@end






@implementation SEECLoginViewController

@synthesize LoginButton;
@synthesize userTextField;
@synthesize passwordTextField;



int direction=1;
int shakes = 0;


-(void)executeLogin:(id)sender
{
    [self dismissModalViewControllerAnimated:YES];
}

- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
}





//--this segue is working
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    NSLog(@"segue at login");
    if ([[segue identifier] isEqualToString:@"smenu"]) {
        NSLog(@"  dentro de if  ");
        
    }
 
}




- (void)viewDidLoad
{
    [super viewDidLoad];
    self.title = @"Login";
	// Do any additional setup after loading the view.
    notificationLabel.text=@"";
    [scroll setScrollEnabled:YES];
   
}




- (void)viewDidUnload
{
    [notificationLabel release];
    notificationLabel = nil;
    [self setLoginButton:nil];
    [super viewDidUnload];
    // Release any retained subviews of the main view.

    
}


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
	return (interfaceOrientation == UIInterfaceOrientationLandscapeRight);
}





- (IBAction)scrollOn:(id)sender{

    NSLog(@"on");
    
    [scroll setContentOffset:CGPointMake(0, 200) animated:YES];
    
}


- (IBAction)scrollOff:(id)sender{
    NSLog(@"off");
    
    [scroll setContentOffset:CGPointMake(0, 0) animated:YES];
    
    

}




- (IBAction)login:(id)sender {

    [self setLogin];
        
}






-(void) setLogin{

    direction=1;
    shakes = 0;
    if(  userTextField.text.length>1 && passwordTextField.text.length>1   ){
        NSDictionary *recoverInfo  =  [self recoverInfo:  @"seec_login" : @"guid == %@": userTextField.text: @"diffgram" : @"NewDataSet" ];
        
        if(recoverInfo!=nil ){
            NSString *recoverPass = [NSString stringWithFormat:@"%@", [recoverInfo valueForKey:@"guidPassword"]];
            NSString *logId = [NSString stringWithFormat:@"%@", [recoverInfo valueForKey:@"id"]];
            NSString *FK_userId = [NSString stringWithFormat:@"%@", [recoverInfo valueForKey:@"FK_userId"]];
            
            [[SEECUser sharedInstance] initUserId:logId];
            [[SEECUser sharedInstance] initFK_userId:FK_userId];
            
            if( [passwordTextField.text isEqualToString: recoverPass]  ){
                
                //clean
                userTextField.text=@"";
                passwordTextField.text=@"";
                notificationLabel.text=@"";
                
                //navigation
                UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
                SEECReportesViewController *menu = [storyboard instantiateViewControllerWithIdentifier:@"SEECMenuViewController"];
                
                //self navigation push
                [self.navigationController pushViewController:menu animated:YES];
            }else{
                //clean
                notificationLabel.text=@"Usuario Invalido";
                userTextField.text=@"";
                passwordTextField.text=@"";
                [self goingshakeButton:LoginButton];
            }
        }else{
            notificationLabel.text=@"";
            userTextField.text=@"";
            passwordTextField.text=@"";
            [self goingshakeButton:LoginButton];
        }
    }else{[self goingshakeButton:LoginButton];}


}



-(NSDictionary *) recoverInfo: (NSString *) fileJson
                         : (NSString *) query
                         : (NSString *) queryValues
                         : (NSString *) dataRoot
                         : (NSString *) setValue{
    
    NSURL *url = [[NSBundle mainBundle] URLForResource:fileJson withExtension:@"json"];
    
    NSData *data = [NSData dataWithContentsOfURL:url];
    
    NSError *error = nil;
    
    NSDictionary *response = AFJSONDecode(data, &error);
    
    NSPredicate *predicate = [NSPredicate predicateWithFormat: query,queryValues];
    
    
    NSArray *items =[[[response valueForKey:dataRoot] valueForKey:setValue] filteredArrayUsingPredicate:predicate];
    
    NSDictionary *currentObject =nil;
    
     if( [items count] > 0 ){
       currentObject = [ items objectAtIndex:0];
     }
    
    return currentObject;
    
}






- (void)goingshakeTextField:(UITextField *)textField
{
    
    [UIView animateWithDuration:0.3
                     animations:^{


                          textField.transform = CGAffineTransformMakeTranslation(20*direction, 0);
                         
                         
                     }
                     completion:^(BOOL finished) {
                     
                         
                      
                         if(shakes >= 10)
                         {
                             textField.transform = CGAffineTransformIdentity;
                             return;
                         }
                         shakes++;
                         direction = direction * -1;
                         [self goingshakeTextField:textField];
                     
                     }];
}






- (void)goingshakeButton:(UIButton *)uiButton
{
    
    [UIView animateWithDuration:0.3
                     animations:^{
                         
                         
                         uiButton.transform = CGAffineTransformMakeTranslation(35*direction, 0);
                         
                         
                     }
                     completion:^(BOOL finished) {
                         
                         
                         
                         if(shakes >= 10)
                         {
                             uiButton.transform = CGAffineTransformIdentity;
                             return;
                         }
                         shakes++;
                         direction = direction * -1;
                         [self goingshakeButton:uiButton];
                         
                     }];
}







- (void)textFieldDidBeginEditing:(UITextField *)textField{
   
    NSLog(@"enter ");

 }




- (void)dealloc {
    [notificationLabel release];
    [LoginButton release];
    [super dealloc];
}

@end
