/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import <UIKit/UIKit.h>

@interface SEECReportViewController : UIViewController{
    
    
  	NSArray		*suggestions;
    
}



@property (retain) UIPopoverController *popOverControllerForBranches;


@property (retain) UIPopoverController *popOverByType;

//seacr by type
@property (nonatomic, retain) IBOutlet UITableView *SearchByType;


//notification for branch
-(void)selectBranchWithNotification:(NSNotification *)notification;

//notification for type search
-(void)selectPhaseWithNotification:(NSNotification *)notification;

//notifications
-(void)selectBranchSearchedWithNotification:(NSNotification *)notification;




- (IBAction)goAuditevaluation:(id)sender;

//Json Search States, City and Branch
-(IBAction)showStatesList:(id)sender;


// show search type
- (IBAction)showSearch:(id)sender;

//go to search dealers by type
@property (retain, nonatomic) IBOutlet UIButton *SearchTypeGo;


//display Data of branch

@property (retain, nonatomic) IBOutlet UILabel *branchName;
@property (retain, nonatomic) IBOutlet UILabel *stateName;
@property (retain, nonatomic) IBOutlet UILabel *cityName;
@property (retain, nonatomic) IBOutlet UILabel *saleType;
@property (retain, nonatomic) IBOutlet UILabel *isvNumber;
@property (retain, nonatomic) IBOutlet UILabel *zoneName;


@property (retain, nonatomic) IBOutlet UILabel *SearchLabel;


- (IBAction)goSearchByType:(id)sender;

@property (retain, nonatomic) IBOutlet UITextField *searchValueForm;


@end
