/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import "SEECUser.h"

@implementation SEECUser


//---login
@synthesize userId;
@synthesize userName;


//--audit
@synthesize stateSelected;
@synthesize citySelected;
@synthesize dealerSelected;
@synthesize phaseNumLabel;

//---dealer
@synthesize  saleType;
@synthesize  subZone;
@synthesize  branchType;
@synthesize  branchId;
@synthesize adress;
@synthesize phone;
@synthesize bName;


//--activity
@synthesize  mth;
@synthesize  act;
@synthesize  obj;
@synthesize code;
@synthesize std;
@synthesize evid;
@synthesize typeOfBreach;




//--seec_evaluation
@synthesize LK_evaluationId;
@synthesize FK_userId;
@synthesize FK_manualId;
@synthesize FK_standardId;
@synthesize FK_activityId;
@synthesize FK_branchId;
@synthesize FK_departmentId;
@synthesize FK_ownerId;
@synthesize phaseNum;
@synthesize reached;
@synthesize notReached;
@synthesize notApplicable;
@synthesize certificationLevel;
@synthesize commentTitle;
@synthesize comment;
@synthesize recommendation;
@synthesize createdDate;
@synthesize actionPlan;
@synthesize estimatedImpDate;
@synthesize actionPlanDate;
@synthesize actionPlanComment;
@synthesize commentDate;
@synthesize actionPlanApprove;
@synthesize furtherContribution;
@synthesize tracking;
@synthesize specialStandard;


//--search paramethers
@synthesize searchType;
@synthesize searchValue;

///////seee_auditDate
@synthesize LK_auditDateId;
@synthesize auditDate;


///////seec_owner
@synthesize LK_ownerId;
@synthesize isvNumber;
@synthesize firstName;
@synthesize lastName;
@synthesize ownerUser;

///////seec_indicator


@synthesize LK_indCveId;
@synthesize fMonth;
@synthesize sMonth;
@synthesize tMonth;
@synthesize isv_R1;
@synthesize isc_R1;
@synthesize isv_R2;
@synthesize isc_R2;
@synthesize isv_R3;
@synthesize isc_R3;
@synthesize cMonth;
@synthesize isv_Current;
@synthesize isc_Current;





//--

+(SEECUser *)sharedInstance {
    static SEECUser *myinstance = nil;
    if(nil==myinstance){
        myinstance =[[[self class] alloc] init];
        //user
        myinstance.userId = @"";
        myinstance.userName = @"";
        
        //audit
        myinstance.stateSelected=@"";
        myinstance.citySelected=@"";
        myinstance.dealerSelected=@"";
        myinstance.phaseNumLabel=@"";
        
        //--dealer
        myinstance.subZone=@"";
        myinstance.saleType=@"";
        myinstance.branchType=@"";
        myinstance.branchId=@"";
        myinstance.adress=@"";
        myinstance.phone=@"";
        myinstance.bName=@"";
        
        
        //----activity
        myinstance.obj= @"";
        myinstance.mth= @"";
        myinstance.act= @"";
        myinstance.code=@"";
        myinstance.std=@"";
        myinstance.evid=@"";
        myinstance.typeOfBreach=@"";
        //--more values
        
        
        ////seec_evaluation
        myinstance.LK_evaluationId=@"";
        myinstance.FK_userId= @"";
        myinstance.FK_manualId= @"";
        myinstance.FK_standardId= @"";
        myinstance.FK_activityId= @"";
        myinstance.FK_branchId= @"";
        myinstance.FK_departmentId= @"";
        myinstance.FK_ownerId= @"";
        myinstance.phaseNum= @"";
        myinstance.reached= @"";
        myinstance.notReached= @"";
        myinstance.notApplicable= @"";
        myinstance.certificationLevel= @"";
        myinstance.commentTitle= @"";
        myinstance.comment= @"";
        myinstance.recommendation= @"";
        myinstance.createdDate= @"";
        myinstance.actionPlan= @"";
        myinstance.estimatedImpDate= @"";
        myinstance.actionPlanDate= @"";
        myinstance.actionPlanComment= @"";
        myinstance.commentDate= @"";
        myinstance.actionPlanApprove= @"";
        myinstance.furtherContribution= @"";
        myinstance.tracking= @"";
        myinstance.specialStandard= @"";
        
        
        //seec search
        myinstance.searchType=@"";
        myinstance.searchValue=@"";
        
        
        //seee_auditDate
        
        myinstance.LK_auditDateId=@"";
        myinstance.auditDate=@"";
        
        
        
        //seec_owner
        
        myinstance.LK_ownerId=@"";
        myinstance.isvNumber=@"";
        myinstance.firstName=@"";
        myinstance.lastName=@"";
        myinstance.ownerUser=@"";
        
        
        //seec_indicator
        
        myinstance.LK_indCveId=@"";
        myinstance.fMonth=@"";
        myinstance.sMonth=@"";
        myinstance.tMonth=@"";
        myinstance.isv_R1=@"";
        myinstance.isc_R1=@"";
        myinstance.isv_R2=@"";
        myinstance.isc_R2=@"";
        myinstance.isv_R3=@"";
        myinstance.isc_R3=@"";
        myinstance.cMonth=@"";
        myinstance.isv_Current=@"";
        myinstance.isc_Current=@"";

        
        
        
        
    }
    return myinstance;
}




//setter of login
- (id)initUserId:(NSString *)userId_{
    self.userId=userId_;
    return self;
}


- (id)initUserName:(NSString *)userName_{
    self.userName=userName_;
    return self;
}




//setter for Auditoria
- (id)initState:(NSString *)statein{
    self.stateSelected=statein;
    return self;
}


- (id)initCity:(NSString *)cityin{
    self.citySelected=cityin;
    return self;
}



- (id)initDealer:(NSString *)dealerin{
    self.dealerSelected=dealerin;
    return self;
}



- (id)initSaleType:(NSString *)saletypein{
    self.saleType=saletypein;
    return self;
    }


- (id)initPhaseLabel:(NSString *)phaseNumLabelin{
    self.phaseNumLabel=phaseNumLabelin;
    return self;
}


///---dealer

- (id)initSubZone:(NSString *)subZonein{
    self.subZone = subZonein;
    return self;
   }



- (id)initBranchType:(NSString *)branchTypein{
    self.branchType=branchTypein;
    return self;
 }


- (id)initBranchId:(NSString *)branchIdin{
    self.branchId=branchIdin;
   return self;
}


- (id)initAdress:(NSString *)adressin{
    self.adress=adressin;
    return self;

}

- (id)initPhone:(NSString *)phonein{
    self.phone=phonein;
    return self;
}

- (id)initbName:(NSString *)bNamein{
    self.bName=bNamein;
    return self;
}



//---activity


- (id)initObj:(NSString *)objin{self.obj=objin;return self;}


- (id)initMth:(NSString *)mthin{self.mth=mthin;return self;}


- (id)initAct:(NSString *)actin{self.act=actin;return self;}


- (id)initCode:(NSString *)codein{
    self.code=codein;
    return self;
}


- (id)initStd:(NSString *)Stdin{
    self.std=Stdin;
    return self;
}


- (id)initEvid:(NSString *)evidin{
    self.evid=evidin;
    return self;
}


- (id)inittypeOfBreach:(NSString *)typeOfBreachIn{
    self.typeOfBreach=typeOfBreachIn;
    return self;
}





//seec evaluation


-(id)initLK_evaluationId:(NSString *)LK_evaluationId_{
    self.LK_evaluationId=LK_evaluationId_;
    return self;
}


- (id)initFK_userId:(NSString *)FK_userId_{
    self.FK_userId=FK_userId_;
    return self;
}

- (id)initFK_manualId:(NSString *)FK_manualId_{
    
    self.FK_manualId=FK_manualId_;
    return self;
}
- (id)initFK_standardId:(NSString *)FK_standardId_{

    self.FK_standardId=FK_standardId_;
   return self;   
}

- (id)initFK_activityId:(NSString *)FK_activityId_{
    self.FK_activityId=FK_activityId_;
    return self;
}

- (id)initFK_branchId:(NSString *)FK_branchId_{
    self.FK_branchId=FK_branchId_;
    return self;
}

- (id)initFK_departmentId:(NSString *)FK_departmentId_{
    
    self.FK_departmentId = FK_departmentId_;
    return self;
    
}

- (id)initFK_ownerId:(NSString *)FK_ownerId_{
    self.FK_ownerId=FK_ownerId_;
    return self;
}

- (id)initphaseNum:(NSString *)phaseNum_{
    self.phaseNum=phaseNum_;
    return self;
}


- (id)initreached:(NSString *)reached_{
    self.reached=reached_;
    return self;
}

- (id)initnotReached:(NSString *)notReached_{
    self.notReached=notReached_;
    return self;
}

-(id)initnotApplicable:(NSString *)notApplicable_{
    self.notApplicable=notApplicable_;
    return self;
}

- (id)initcertificationLevel:(NSString *)certificationLevel_{
    self.certificationLevel=certificationLevel_;
    return self;
}

- (id)initcommentTitle:(NSString *)commentTitle_{
    self.commentTitle=commentTitle_;
    return self;
}

- (id)initcomment:(NSString *)comment_{
    self.comment=comment_;
    return self;
}

- (id)initrecommendation:(NSString *)recommendation_{
    self.recommendation=recommendation_;
    return self;
}
- (id)initcreatedDate:(NSString *)createdDate_{
    self.createdDate=createdDate_;
    return self;
}

- (id)initactionPlan:(NSString *)actionPlan_{
    self.actionPlan=actionPlan_;
    return self;
}

- (id)initestimatedImpDate:(NSString *)estimatedImpDate_{
    self.estimatedImpDate=estimatedImpDate_;
    return self;
}

- (id)initactionPlanDate:(NSString *)actionPlanDate_{
    self.actionPlanDate=actionPlanDate_;
    return self;
}

- (id)initactionPlanComment:(NSString *)actionPlanComment_{
    self.actionPlanComment=actionPlanComment_;
    return self;
}

- (id)initcommentDate:(NSString *)commentDate_{
    self.commentDate=commentDate_;
    return self;
}

- (id)initactionPlanApprove:(NSString *)actionPlanApprove_{
    self.actionPlanApprove = actionPlanApprove_;
    return self;
}


- (id)initfurtherContribution:(NSString *)furtherContribution_{
    self.furtherContribution=furtherContribution_;
    return self;
}

- (id)inittracking:(NSString *)tracking_{
    self.tracking=tracking_;
    return self;
}

- (id)initspecialStandard:(NSString *)specialStandard_{
    self.specialStandard=specialStandard_;
    return self;
}



//seec search

- (id)initSearchWithType:(NSString *)type_{
    self.searchType = type_;
     return self;
}



- (id)initSearchValue:(NSString *)value_{
    self.searchValue = value_;
    return self;
}


//seee_auditDate

- (id)initLK_auditDateId:(NSString *)LK_auditDateId_{
    self.LK_auditDateId = LK_auditDateId_;
    return self;
}

- (id)initAuditDate:(NSString *)auditDate_{
    self.AuditDate = auditDate_;
    return self;
}




//seec_owner


- (id)initIsvNumber:(NSString *)isvNumber_{
    self.isvNumber = isvNumber_;
    return self;
}
- (id) initFirstName:(NSString *) firstName_{
    self.firstName = firstName_;
    return self;
}
- (id) initLastName:(NSString *) lastName_{
    self.lastName = lastName_;
    return self;
}
- (id) initOwnerUser:(NSString *)ownerUser_{
    self.ownerUser = ownerUser_;
    return self;
}

//seec_indicator


- (id) initLK_indCveId:(NSString *)LK_indCveId_ {
    self.LK_indCveId =  LK_indCveId_;
    return self;
}

- (id) initFMonth:(NSString *)fMonth_{
    self.fMonth = fMonth_;
    return self;
}
- (id) initSMonth:(NSString *)sMonth_ {
    self.sMonth = sMonth_;
    return self;
}
- (id) initTMonth:(NSString *) tMonth_{
    self.tMonth = tMonth_;
    return self;
}

- (id) initIsv_R1:(NSString *)isv_R1_ {
    self.isv_R1 = isv_R1_;
    return self;
}
- (id) initIsc_R1:(NSString *)isc_R1_{
    self.isc_R1 =  isc_R1_;
    return self;
}
- (id)initIsv_R2 :(NSString *)isv_R2_ {
    self.isv_R2 = isv_R2_;
    return self;
}
- (id)initIsc_R2 :(NSString *) isc_R2_{
    self.isc_R2 =  isc_R2_;
    return self;
}
- (id) initIsv_R3:(NSString *)isv_R3_ {
    self.isv_R3 = isv_R3_;
    return self;
}
- (id) initIsc_R3:(NSString *)isc_R3_ {
    self.isc_R3 =isc_R3_;
    return self;
}
- (id) initCMonth:(NSString *) cMonth_{
    self.cMonth = cMonth_;
    return self;
}
- (id) initIsv_Current:(NSString *) isv_Current_{
    self.isv_Current =  isv_Current_;
    return self;
}
- (id) initIsc_Current:(NSString *) isc_Current_{
    self.isc_Current = isc_Current_;
    return self;
}


//filing

-(id)initFileName_:(NSString *)fileName{
    self.fileName_=fileName;
    return self;
}


-(id)initEvaluationID_:(NSString *)evaluationID{
    self.evaluationID_=evaluationID;
    return self;
}




@end
