/*
 
 Product is designed by MINDBITS,  trade mark registered in Mexico.
 
 
 For tecnical support:
 
 www.mindbits.com.mx
 info@mindbits.com.mx
 ventas@mindbits.com.mx
 
 All right reserved, Do not edit this file!.
 sotware product delivered and tested under standards  by pwc mexico.
 
 Warning: this product is writting in production enviroment.
 
 This is a copy of original software, administered  by an third part,  so this software its License is distributed on an "AS IS",  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. the trade mark MINDBITS is not resposable for errors or mistakes in PWC / NISSAN production enviroments. Open Sources libraries show its own conditions of distributions.
 
 */ 


#import "SEECSSICSIViewController.h"
#import "SEECAuditoriaViewController.h"


@interface SEECSSICSIViewController ()

@end

@implementation SEECSSICSIViewController
@synthesize mlast;
@synthesize mpenultimate;
@synthesize mantepenultimate;
@synthesize ultimateSSI;
@synthesize penulSSI;
@synthesize anteSSI;
@synthesize ultimateCSI;
@synthesize penCSI;
@synthesize anteCSI;

//month selector
bool flagmayo = NO;



- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        // Custom initialization
    }
    return self;
}



- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view.
}

- (void)viewDidUnload
{
    [self setMlast:nil];
    [self setMpenultimate:nil];
    [self setMantepenultimate:nil];
    [self setUltimateSSI:nil];
    [self setPenulSSI:nil];
    [self setAnteSSI:nil];
    [self setUltimateCSI:nil];
    [self setPenCSI:nil];
    [self setAnteCSI:nil];
    [super viewDidUnload];
    // Release any retained subviews of the main view.
}


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return (interfaceOrientation == UIInterfaceOrientationLandscapeRight);
}



- (void)dealloc {
    [mlast release];
    [mpenultimate release];
    [mantepenultimate release];
    [ultimateSSI release];
    [penulSSI release];
    [anteSSI release];
    [ultimateCSI release];
    [penCSI release];
    [anteCSI release];
    [super dealloc];
}






- (IBAction)textDidChange:(id)textField{

   
    [self monthAutoFillTF:mlast];
    
       
}




- (IBAction)textDidChange1:(id)textField{

    [self monthAutoFillTF:mpenultimate];

}



- (IBAction)textDidChange2:(id)textField{

    [self monthAutoFillTF:mantepenultimate];

}





- (IBAction)saveSSICSI:(id)sender {

  
  
    
    
    NSLog(@"dismiss on save ...for back");
    [self dismissModalViewControllerAnimated:YES];

}





- (IBAction)back:(id)sender {
    
    
    NSLog(@"dismiss modal...for back");
    [self dismissModalViewControllerAnimated:YES];
    
}



-(void)monthAutoFillTF: (UITextField *) tf{

    
    //----enero
    if( [tf.text isEqualToString:@"ene"] ||
       [tf.text isEqualToString:@"ENE"])
    {
        
        NSLog(@" setting enero ");
        [tf.text uppercaseString];
        tf.text=@"ENERO";
    }
    
    if( [tf.text hasPrefix:@"ene"] ||
       [tf.text hasPrefix:@"ENE"] ){
        if(tf.text.length==4){
            tf.text =@"";
        }
    }
    
    //backspace
    if( [tf.text hasPrefix:@"ene"] ||
       [tf.text hasPrefix:@"ENE"] ){
        if(tf.text.length>5){
            tf.text =@"ENERO";
        }
    }
    
    
    //---febrero
    //star with feb
    if( [tf.text isEqualToString:@"feb"] ||
       [tf.text isEqualToString:@"FEB"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"FEBRERO";
    }
    
    
    //star with feb
    if( [tf.text hasPrefix:@"feb"] ||
       [tf.text hasPrefix:@"FEB"] ){
        if(tf.text.length==6){
            tf.text =@"";
        }
    }
    
    //backspace
    if( [tf.text hasPrefix:@"feb"] ||
       [tf.text hasPrefix:@"FEB"] ){
        if(tf.text.length>7){
            tf.text =@"FEBRERO";
        }
    }
    
    
    
    //------marzo
    
    if( [tf.text isEqualToString:@"mar"] ||
       [tf.text isEqualToString:@"MAR"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"MARZO";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"mar"] ||
       [tf.text hasPrefix:@"MAR"] ){
        if(tf.text.length==4){
            tf.text =@"";
        }
    }
    
    //more to MARZO
    if( [tf.text hasPrefix:@"mar"] ||
       [tf.text hasPrefix:@"MAR"] ){
        if(tf.text.length>5){
            tf.text =@"MARZO";
        }
    }
    
    
    //--------abril
    
    
    if( [tf.text isEqualToString:@"abr"] ||
       [tf.text isEqualToString:@"ABR"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"ABRIL";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"abr"] ||
       [tf.text hasPrefix:@"ABR"] ){
        if(tf.text.length==4){
            tf.text =@"";
        }
    }
    
    //more to ABRIL
    if( [tf.text hasPrefix:@"abr"] ||
       [tf.text hasPrefix:@"ABR"] ){
        if(tf.text.length>5){
            tf.text =@"ABRIL";
        }
    }
    
    
    //-------------mayo
    
    
    
    if( ( [tf.text isEqualToString:@"may"] ||
         [tf.text isEqualToString:@"MAY"] ) &&  (flagmayo == NO)  )
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"MAYO";      
        flagmayo = YES;
        
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"may"] ||
       [tf.text hasPrefix:@"MAY"] ){
        if(tf.text.length==3 && flagmayo){
            tf.text =@"";
            flagmayo = NO;
            
        }
    }
    
    //more to MAYO
    if( [tf.text hasPrefix:@"may"] ||
       [tf.text hasPrefix:@"MAY"] ){
        if(tf.text.length>4){
            tf.text =@"MAYO";            
            flagmayo = YES;
            
            
        }
    }
    
    
    
    
    //-----junio
    
    if( [tf.text isEqualToString:@"jun"] ||
       [tf.text isEqualToString:@"JUN"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"JUNIO";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"jun"] ||
       [tf.text hasPrefix:@"JUN"] ){
        if(tf.text.length==4){
            tf.text =@"";
        }
    }
    
    //more to JUNIO
    if( [tf.text hasPrefix:@"jun"] ||
       [tf.text hasPrefix:@"JUN"] ){
        if(tf.text.length>5){
            tf.text =@"JUNIO";
        }
    }
    
    
    //-----julio
    
    if( [tf.text isEqualToString:@"jul"] ||
       [tf.text isEqualToString:@"JUL"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"JULIO";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"jul"] ||
       [tf.text hasPrefix:@"JUL"] ){
        if(tf.text.length==4){
            tf.text =@"";
        }
    }
    
    //more to JULIO
    if( [tf.text hasPrefix:@"jul"] ||
       [tf.text hasPrefix:@"JUL"] ){
        if(tf.text.length>5){
            tf.text =@"JULIO";
        }
    }
    
    
    //-----agosto
    
    if( [tf.text isEqualToString:@"ago"] ||
       [tf.text isEqualToString:@"AGO"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"AGOSTO";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"ago"] ||
       [tf.text hasPrefix:@"AGO"] ){
        if(tf.text.length==5){
            tf.text =@"";
        }
    }
    
    //more to AGOSTO
    if( [tf.text hasPrefix:@"ago"] ||
       [tf.text hasPrefix:@"AGO"] ){
        if(tf.text.length>6){
            tf.text =@"AGOSTO";
        }
    }
    
    
    
    //-----septiembre
    
    if( [tf.text isEqualToString:@"sep"] ||
       [tf.text isEqualToString:@"SEP"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"SEPTIEMBRE";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"sep"] ||
       [tf.text hasPrefix:@"SEP"] ){
        if(tf.text.length==9){
            tf.text =@"";
        }
    }
    
    //more to SEPTIEMBRE
    if( [tf.text hasPrefix:@"sep"] ||
       [tf.text hasPrefix:@"SEP"] ){
        if(tf.text.length>10){
            tf.text =@"SEPTIEMBRE";
        }
    }
    
    
    //-----octubre
    
    if( [tf.text isEqualToString:@"oct"] ||
       [tf.text isEqualToString:@"OCT"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"OCTUBRE";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"oct"] ||
       [tf.text hasPrefix:@"OCT"] ){
        if(tf.text.length==6){
            tf.text =@"";
        }
    }
    
    //more to OCTUBRE
    if( [tf.text hasPrefix:@"oct"] ||
       [tf.text hasPrefix:@"OCT"] ){
        if(tf.text.length>7){
            tf.text =@"OCTUBRE";
        }
    }
    
    //-----noviembre
    
    if( [tf.text isEqualToString:@"nov"] ||
       [tf.text isEqualToString:@"NOV"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"NOVIEMBRE";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"nov"] ||
       [tf.text hasPrefix:@"NOV"] ){
        if(tf.text.length==8){
            tf.text =@"";
        }
    }
    
    //more to NOVIEMBRE
    if( [tf.text hasPrefix:@"nov"] ||
       [tf.text hasPrefix:@"NOV"] ){
        if(tf.text.length>9){
            tf.text =@"NOVIEMBRE";
        }
    }
    
    
    //-----diciembre
    
    if( [tf.text isEqualToString:@"dic"] ||
       [tf.text isEqualToString:@"DIC"])
    {
        
        NSLog(@" setting febrero ");
        [tf.text uppercaseString];
        tf.text=@"DICIEMBRE";
    }
    
    
    //backspace
    if( [tf.text hasPrefix:@"dic"] ||
       [tf.text hasPrefix:@"DIC"] ){
        if(tf.text.length==8){
            tf.text =@"";
        }
    }
    
    //more to DICIEMBRE
    if( [tf.text hasPrefix:@"dic"] ||
       [tf.text hasPrefix:@"DIC"] ){
        if(tf.text.length>9){
            tf.text =@"DICIEMBRE";
        }
    }


    
}







- (void)showAlertMsg:(NSString *)msgtext{
    
	NSString *title = @"SEEC iPad";
	UIAlertView* alertView = nil;
	@try {
		alertView = [[UIAlertView alloc] initWithTitle:title message:msgtext delegate:self cancelButtonTitle:@"OK" otherButtonTitles:nil];
		
		[alertView show];
	} @finally {
		if (alertView) {
			[alertView release];
		}
	}
	
	
}





@end
